accounts/urls.py
from django.urls import path
from .views import HomeView, UserLoginView, UserLogoutView, UserView
from . import views

app_name = 'accounts'
urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('regist/', views.regist, name='regist'),
    #path('user_login/', views.user_login, name='user_login'),
    path('user_login/', UserLoginView.as_view(), name='user_login'),
    path('user_logout/', UserLogoutView.as_view(), name='user_logout'),
    path('user/', UserView.as_view(), name='user'),
]

ecsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('stores/', include('stores.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stores/urls.py
from django.urls import path
from .views import (
    ProductListView, ProductDetailView, 
    add_product, CartItemsView, CartUpdateView,
    CartDeleteView, InputAddressView, ConfirmOrderView,
    OrderSuccessView,
)


app_name='stores'
urlpatterns = [
    path('product_list/', ProductListView.as_view(), name='product_list'),
    path('product_detail/<int:pk>', ProductDetailView.as_view(), name='product_detail'),
    path('add_product/', add_product, name='add_product'),
    path('cart_items/', CartItemsView.as_view(), name='cart_items'),
    path('update_cart/<int:pk>', CartUpdateView.as_view(), name='update_cart'),
    path('delete_cart/<int:pk>', CartDeleteView.as_view(), name='delete_cart'),
    path('input_address/', InputAddressView.as_view(), name='input_address'),
    path('input_address/<int:pk>', InputAddressView.as_view(), name='input_address'),
    path('confirm_order/', ConfirmOrderView.as_view(), name='confirm_order'),
    path('order_success/', OrderSuccessView.as_view(), name='order_success'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ja">
   <head>
      <meta charset="utf-8">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      {% block customcss %}
      {% endblock customcss %}
   </head>
   <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'accounts:home' %}">ホーム</a>
        {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'stores:product_list' %}">商品一覧</a>
        <a class="navbar-brand" href="{% url 'stores:cart_items' %}">カートへ</a>
        <a class="navbar-brand" href="{% url 'accounts:user_logout' %}">ログアウト</a>
        {% else %}
        <a class="navbar-brand" href="{% url 'accounts:user_login' %}">ログイン</a>
        <a class="navbar-brand" href="{% url 'accounts:regist' %}">ユーザー登録</a>
        {% endif %}
      </nav>
      {% block content %}{% endblock %}
   </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}
<h2 class="text-center py-5">ホーム画面です</h2>
<h2 class="text-center">商品一覧から商品をご覧になれます</h2>
{% endblock %}

templates/regist.html
<!DOCTYPE html>
<html lang="ja">
<head>
   <meta charset="utf-8">
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
   {% load static %}
   {% block customcss %}
   <link href="{% static 'style.css' %}" rel="stylesheet">
   <style>
      .form-signin input[type="text"] {
        margin-bottom: -1px;
        border-bottom-left-radius: 0;
        border-bottom-right-radius: 0;
      }
      .form-signin input[type="email"] {
        margin-top: -1px;
        margin-bottom: -1px;
        border-radius: 0;
      }
   </style>
   {% endblock customcss %}
</head>
{% block content %}
<body class="text-center">
   <main class="form-signin">
      <h1 class="h3 mb-3 fw-normal">ユーザ登録</h1>
      {% if regist_form.password.errors or regist_form.errors%}
         <div>
               <ul class="alert alert-danger list-unstyled">
                  {% for error in regist_form.password.errors %}
                  <li>{{ error }}</li>
                  {% endfor %}
                  {% for field in regist_form %}
                     {% for error in field.errors %}
                        <li>{{ error }}</li>
                     {% endfor %}
                  {% endfor %}
               </ul>
         </div>
      {% endif %}
      <form method="post">
         {% csrf_token %}
         {% for item in regist_form %}
            <input type="{{ item.field.widget.input_type }}" class="form-control" {% if item.field.required %}required{% endif %} placeholder="{{item.label}}" name="{{item.name}}">
         {% endfor %}
         <button class="w-100 btn btn-lg btn-primary" type="submit">登録</button>
      </form>
      <a class="navbar-brand" href="{% url 'accounts:user_login' %}">ログイン</a>
   </main>
</body>
{% endblock %}

templates/user.html
{% extends 'base.html' %}
{% block content %}
<h1>ユーザ画面です。ログインが必要な画面です</h1>
{% endblock %}

templates/user_login.html
<!DOCTYPE html>
<html lang="ja">
<head>
   <meta charset="utf-8">
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
   {% load static %}
   {% block customcss %}
   <link href="{% static 'style.css' %}" rel="stylesheet">
   {% endblock customcss %}
</head>
{% block content %}

<body class="text-center">
   <main class="form-signin">
      {% if form.errors %}
         <div class="alert alert-danger" role="alert">
            {{form.non_field_errors}}
         </div>
      {% endif %}
      <h1 class="h3 mb-3 fw-normal py-3">ログイン</h1>
      <form method="post" class="form-group">
         {% csrf_token %}
         {% for item in form %}
            {% if item.field.widget.input_type == 'checkbox' %}
               <div class="checkbox mb-3">
                  <label>
                     <input type="{{item.field.widget.input_type}}" name="{{item.name}}"> {{item.label}}
                  </label>
               </div>
            {% else %}
               <input type="{{item.field.widget.input_type}}" class="form-control" {% if item.field.required %}required{% endif %} placeholder="{{item.label}}" name="{{item.name}}">
            {% endif %}
         {% endfor %}
         <input type="hidden" name="next" value="{{ request.GET.next }}">
         <button class="w-100 btn btn-lg btn-primary" type="submit">ログイン</button>
      </form>
      <a class="navbar-brand" href="{% url 'accounts:regist' %}">ユーザー登録</a>
   </main>
</body>
{% endblock %}